apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: server
        image: mohamedabid1/email:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
          requests:
            memory: "180Mi"
            cpu: "200m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 8080
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000 
          runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  type: ClusterIP
  selector:
    app: email
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080